server:
  port: 8083
fts:
  db:
    database: fts-product
    host: 127.0.0.1
    port: 3307
    username: root
    pw: root123
  swagger:
    title: 基金销售系统产品服务接口文档
    description: 基金销售系统产品服务接口文档
    package: com.github.JLQusername.controller
